<?php

/**
 * @file
 * Primary module hooks for AS module module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view().
 */
function as_module_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityType()->id() === 'node') {
    $build['awesome'] = [
      '#markup' => '<marquee>This is awesome</marquee>',
      '#allowed_tags' => ['marquee'],
    ];
  }
}
